# Generated by Django 6.0 on 2025-12-25 19:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='id',
            field=models.CharField(default=app.models.generate_paste_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
